version: '3.3'

services:
    api:
        container_name: gerador-tokens_api
        build: .
        command: 'yarn start'
        ports:
            - '3000:3000'
        volumes:
            - .:/usr/src
        restart: always
        depends_on: 
          - db
    database:
      container_name: gerador-tokens_database
      image: postgres:14.0-alpine
      ports:
        - "5432:5432"
      environment:
        POSTGRES_DB: token_manager
        POSTGRES_USER: root
        POSTGRES_PASSWORD: T0m02c4f3zinho
      volumes:
        - "/etc/backups/data-postgres/gerador-tokens:/var/lib/postgresql/data"
      restart: always